### ISSUE TITLE
Romanian T cedilla

### ISSUE THREAD

**Issue by vv-monsalve** [floriankarsten/montagu-slab#12]
![Screen Shot 2021-06-24 at 21 29 24](https://user-images.githubusercontent.com/48698976/123371600-b15d2d00-d547-11eb-9456-df7a94b5cccb.png)

Hi @mightybart,

You might want to read [this Typedrawers issue](https://typedrawers.com/discussion/318/tcomma-and-tcedilla) and [this Glyphs App tutorial](https://glyphsapp.com/learn/localize-your-font-romanian-and-moldovan) to change de the `Tcedilla` to include the Romanian accents for the T and the {locl} feature for it.

**Comment by vv-monsalve** [comment]
@mightybart please review this issue

**Comment by mightybart** [comment]
I'm using "2. The better-always-consistent-but-sometimes-100%-wrong method" here.

It's like this from the beginning, and I use this method for all my releases (and I think this is a default Glyphs behaviour). Do you prefer the other option for Google Fonts release?

<img width="1288" alt="Screenshot 2021-08-05 at 22 02 04" src="https://user-images.githubusercontent.com/9280418/128413862-3130b8ff-ec89-4122-8c56-3d68143d7a0b.png">

**Comment by mightybart** [comment]
Oh! I'm sorry I didn't realize you probably meant that the implementation does not work. The automatic feature generation apparently does not do it's thing, so I just do it manually.

Here a screenshot from the TTF/OTF file (above was the automatic function in Glyphs source file).

<img width="775" alt="Screenshot 2021-08-05 at 22 19 35" src="https://user-images.githubusercontent.com/9280418/128415930-be0f6b92-e659-4b92-af15-33241a64191f.png">

**Comment by mightybart** [comment]
Fixed now. Using solution "2. The better-always-consistent-but-sometimes-100%-wrong method" from this [https://glyphsapp.com/learn/localize-your-font-romanian-and-moldovan](glyphs tutorial).

Tested in InDesign and LibreOffice.
