### ISSUE TITLE
Browser Preview - Vietnamese 2

### ISSUE THREAD

**Issue by vv-monsalve** [floriankarsten/montagu-slab#13]
Hi @mightybart, I've pulled the latest files in the repo at commit 6440af955df514ddf071d50779aa69400a103874 and these are the new Browser images for Vietnamese.

I've created this new issue to follow up the first one in a cleaner way, as the images tend to be big.

# 144pt Thin 
Results using BrowserStack

**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/128272091-d8672b8d-4c9c-4f70-b027-468b42dcbc8a.png)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/128272084-807c8e5a-fa57-4725-97b4-722f33f07be7.png)
**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/128272090-d8fbac9e-d21f-40ea-90f5-a4996c29cde0.png)

**Comment by vv-monsalve** [comment]
To confirm the above results I've asked a friend to open the HTML directly in Windows. Operative system `Linux Debian`

Some strokes tend to disappear, e.g. the `a` loop

**Chrome Version 88.0.4324.96**
![vietnamese2-09-144CHROME](https://user-images.githubusercontent.com/48698976/128272381-28358943-5d84-4ee1-860e-4101c33b3c82.png)
**Firefos 78**
![vietnamese2-09-144FIREFOX](https://user-images.githubusercontent.com/48698976/128272407-441d42de-2190-44d2-af54-1efdf83146c0.png)
**Linux Debian Web Browser**
![vietnamese2-09-144WEBBROWSER](https://user-images.githubusercontent.com/48698976/128272480-3d346476-e342-4dcd-b2bb-7134f5d98519.png)

**Comment by vv-monsalve** [comment]
# 16pt Thin

Results using BrowserStack

**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/128272917-6304971b-a647-4380-a9c7-a45c0de365c9.png)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/128272913-686a9941-1640-435f-901e-e48062d32cee.png)
**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/128272915-d8551227-861b-4e65-b3a1-c0b2e1a29b2b.png)

**Comment by vv-monsalve** [comment]
Results in Windows. Operative system `Linux Debian`

----
**Chrome Version 88.0.4324.96**
![vietnamese2-09-16CHROME](https://user-images.githubusercontent.com/48698976/128273053-a1cbdb9c-9326-4e9f-abac-0e6825e579d0.png)
----
**Firefox 78**
![vietnamese2-09-16FIREFOX](https://user-images.githubusercontent.com/48698976/128273059-9628ba26-ac12-48e2-9367-57e0e1bf687c.png)
----
**Linux Debian Web Browser**
![vietnamese2-09-16WEBBROWSER](https://user-images.githubusercontent.com/48698976/128273061-3d76dbf0-0abe-4b43-abc6-c16c8b078fba.png)

**Comment by vv-monsalve** [comment]
Latest Browser images after pulling the files in repo at commit 68ebf273ab873a862be8042a4bffaa5c114d064b

They were created at 18pt to inspect if it would be better to set it as the min malue.


**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/130165086-1d2bf8bb-fddc-4168-9a7c-7713e9e8475e.png)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/130165082-7f17dd13-a029-4f1a-aecf-4a925bad59d5.png)
**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/130165084-ecc79340-17dc-45e4-a3f3-206960e98133.png)

**Comment by vv-monsalve** [comment]
This is a comparison image of the current min 16 value Vs. a 18pt but with a subtle increase in the weight to improve the typographic colour without significantly altering the weight of the font.

Weight Value used for this test was 110.

![Montagu-16-18](https://user-images.githubusercontent.com/48698976/130256840-702e1b06-60f8-4464-aac2-1d4eaaa79522.gif)

**Comment by mightybart** [comment]
I tried to find some values that would work for the 16pt size, and weight: 120 & optical size: -40 gives a nice result. The negative opsz value = lower contrast, increased serif weight. I also tried w: 130, opsz: -35, but I think it's not necessary to go that far.

Frame 1: **W: 100** (original)
Frame 2: **W: 120, OPSZ: -40**
Frame 3: **W: 130, OPSZ: -35**

![montagu-16pt](https://user-images.githubusercontent.com/9280418/130297856-9b53e8a5-0562-48d0-bf0f-c85348c0335a.gif)

Static sample **W: 120, OPSZ: -40**

![montagu-16pt-120-40](https://user-images.githubusercontent.com/9280418/130298029-aec9bac8-8c66-4f5f-a270-b0625f4cd624.png)

**Comment by vv-monsalve** [comment]
> Frame 2: **W: 120, OPSZ: -40**

Looks good. Let me know when you have pushed the new files to run some local tests

**Comment by mightybart** [comment]
The current version, after extrapolation end cleaning outlines:

<img width="1023" alt="Screenshot 2021-08-31 at 22 37 49" src="https://user-images.githubusercontent.com/9280418/131572800-5903ad22-82b7-488d-a0a9-3ed02fefcb71.png">

**Comment by vv-monsalve** [comment]
> The current version, after extrapolation end cleaning outlines:

LGTM. I'll pull the latest file in the repo then.

**Comment by mightybart** [comment]
I pushed the new files as you wrote the comment, so hopefully, we're in sync :)

https://github.com/floriankarsten/montagu-slab/commit/1e36474d5fb1d028b435d31ff9c3ebc0cd3b45f6 this is the last commit that corresponds with the image above

**Comment by vv-monsalve** [comment]
New images after pulling files at commit `1e36474`.
They look much better now :D

**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/131934519-320720bd-f7ef-4dba-afda-fa62dd850648.png)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/131934507-d2c9d680-84f9-41dc-9875-19f553eb7a94.png)
**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/131934515-6e91d34a-a8f5-4bbb-b8a1-dca24371afae.png)

**Comment by davelab6** [comment]
Looking good!

**Comment by mightybart** [comment]
Agree ☺️ 👍
