### ISSUE TITLE
Montagu Slab - To Do List for publishing

### ISSUE THREAD

**Issue by vv-monsalve** [floriankarsten/montagu-slab#7]
This would be the To Do list for the publishing process in GF:

- [x] Solve the corner component [issue](https://github.com/floriankarsten/montagu-slab/issues/6)
- [x] Create a build script to ensure scalable font production. It could include the -f flag for flattening components in fontmake and the [gen-stat](https://github.com/googlefonts/gftools/blob/main/bin/gftools-gen-stat.py) tool to create the STAT table.
- [x] Ensure it has an avar table.
- [x] Change the fsType to bit 0, installable.
- [x] Complete the minimum Latin Core encoding coverage (or above if commissioned).
- [x] Set copyright notices to canonical pattern
- [x] Inspect/solve vertical metrics Fail

**Comment by mightybart** [comment]
Fixed.
