### ISSUE TITLE
Kerning Issues

### ISSUE THREAD

**Issue by vv-monsalve** [floriankarsten/montagu-slab#8]
@mightybart producing the proof images it was detected there are some kerning issues.

![Screen Shot 2021-05-06 at 20 24 22](https://user-images.githubusercontent.com/48698976/117384741-4711ff80-aea9-11eb-84f0-0668b0c10bdd.png)
![Screen Shot 2021-05-06 at 20 24 18](https://user-images.githubusercontent.com/48698976/117384744-49745980-aea9-11eb-8e6f-92d5d11b4dab.png)

**Comment by vv-monsalve** [comment]
@mightybart have you completed the punctuation, symbols kerning?

![Screen Shot 2021-08-04 at 20 30 38](https://user-images.githubusercontent.com/48698976/128277192-e45c3926-e5ad-40f5-877e-55dd707b9431.png)
![Screen Shot 2021-08-04 at 20 29 50](https://user-images.githubusercontent.com/48698976/128277190-ac8a3398-f68c-41ab-9736-f24f266e45a9.png)

Some of the present kerning pairs look still a bit loose

![Screen Shot 2021-08-04 at 20 28 12](https://user-images.githubusercontent.com/48698976/128277229-3459ab48-0789-40b8-8fe2-d455058720de.png)
![Screen Shot 2021-08-04 at 20 28 26](https://user-images.githubusercontent.com/48698976/128277232-a662e542-0fe6-4cc3-935e-b551ad894a6d.png)

**Comment by mightybart** [comment]
The uppercase pairs (above) are fixed now.

What's left:

- [x] punct + lowercase
- [x] punct + uppercase
- [ ] punct + numbers
- [ ] numbers + currency
